<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ListFoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $foods = [
            [
                'id_list_food' => Str::random(10),
                'food_name' => 'Nasi Putih',
                'food_calories' => 130.00,
                'cholesterol' => 0.00,
                'fat' => 0.28,
                'protein' => 2.69,
                'carbohydrate' => 28.17,
                'sodium' => 1.00,
                'sugar' => 0.05,
                'weight' => 100.00,
            ],
            [
                'id_list_food' => Str::random(10),
                'food_name' => 'Ayam Goreng',
                'food_calories' => 246.00,
                'cholesterol' => 84.00,
                'fat' => 15.30,
                'protein' => 24.70,
                'carbohydrate' => 0.00,
                'sodium' => 70.00,
                'sugar' => 0.00,
                'weight' => 100.00,
            ],
            [
                'id_list_food' => Str::random(10),
                'food_name' => 'Telur Rebus',
                'food_calories' => 155.00,
                'cholesterol' => 373.00,
                'fat' => 10.60,
                'protein' => 12.60,
                'carbohydrate' => 1.10,
                'sodium' => 124.00,
                'sugar' => 1.10,
                'weight' => 100.00,
            ],
            [
                'id_list_food' => Str::random(10),
                'food_name' => 'Tempe Goreng',
                'food_calories' => 193.00,
                'cholesterol' => 0.00,
                'fat' => 10.80,
                'protein' => 20.80,
                'carbohydrate' => 7.50,
                'sodium' => 9.00,
                'sugar' => 1.70,
                'weight' => 100.00,
            ],
            [
                'id_list_food' => Str::random(10),
                'food_name' => 'Tahu Goreng',
                'food_calories' => 271.00,
                'cholesterol' => 0.00,
                'fat' => 20.70,
                'protein' => 17.20,
                'carbohydrate' => 5.30,
                'sodium' => 11.00,
                'sugar' => 0.60,
                'weight' => 100.00,
            ],
            [
                'id_list_food' => Str::random(10),
                'food_name' => 'Sayur Bayam',
                'food_calories' => 23.00,
                'cholesterol' => 0.00,
                'fat' => 0.26,
                'protein' => 2.86,
                'carbohydrate' => 3.63,
                'sodium' => 79.00,
                'sugar' => 0.42,
                'weight' => 100.00,
            ],
            [
                'id_list_food' => Str::random(10),
                'food_name' => 'Pisang',
                'food_calories' => 89.00,
                'cholesterol' => 0.00,
                'fat' => 0.33,
                'protein' => 1.09,
                'carbohydrate' => 22.84,
                'sodium' => 1.00,
                'sugar' => 12.23,
                'weight' => 100.00,
            ],
            [
                'id_list_food' => Str::random(10),
                'food_name' => 'Apel',
                'food_calories' => 52.00,
                'cholesterol' => 0.00,
                'fat' => 0.17,
                'protein' => 0.26,
                'carbohydrate' => 13.81,
                'sodium' => 1.00,
                'sugar' => 10.39,
                'weight' => 100.00,
            ],
            [
                'id_list_food' => Str::random(10),
                'food_name' => 'Ikan Salmon',
                'food_calories' => 208.00,
                'cholesterol' => 55.00,
                'fat' => 13.00,
                'protein' => 20.00,
                'carbohydrate' => 0.00,
                'sodium' => 59.00,
                'sugar' => 0.00,
                'weight' => 100.00,
            ],
            [
                'id_list_food' => Str::random(10),
                'food_name' => 'Daging Sapi',
                'food_calories' => 250.00,
                'cholesterol' => 90.00,
                'fat' => 15.00,
                'protein' => 26.00,
                'carbohydrate' => 0.00,
                'sodium' => 72.00,
                'sugar' => 0.00,
                'weight' => 100.00,
            ],
            [
                'id_list_food' => Str::random(10),
                'food_name' => 'Kentang Goreng',
                'food_calories' => 312.00,
                'cholesterol' => 0.00,
                'fat' => 15.00,
                'protein' => 3.43,
                'carbohydrate' => 41.44,
                'sodium' => 210.00,
                'sugar' => 0.30,
                'weight' => 100.00,
            ],
            [
                'id_list_food' => Str::random(10),
                'food_name' => 'Roti Tawar',
                'food_calories' => 265.00,
                'cholesterol' => 0.00,
                'fat' => 3.29,
                'protein' => 9.00,
                'carbohydrate' => 49.00,
                'sodium' => 491.00,
                'sugar' => 5.00,
                'weight' => 100.00,
            ],
            [
                'id_list_food' => Str::random(10),
                'food_name' => 'Susu Sapi',
                'food_calories' => 42.00,
                'cholesterol' => 5.00,
                'fat' => 1.00,
                'protein' => 3.40,
                'carbohydrate' => 5.00,
                'sodium' => 44.00,
                'sugar' => 5.00,
                'weight' => 100.00,
            ],
            [
                'id_list_food' => Str::random(10),
                'food_name' => 'Yogurt',
                'food_calories' => 59.00,
                'cholesterol' => 5.00,
                'fat' => 0.40,
                'protein' => 10.00,
                'carbohydrate' => 3.60,
                'sodium' => 36.00,
                'sugar' => 3.20,
                'weight' => 100.00,
            ],
            [
                'id_list_food' => Str::random(10),
                'food_name' => 'Mie Instan',
                'food_calories' => 448.00,
                'cholesterol' => 0.00,
                'fat' => 17.60,
                'protein' => 9.40,
                'carbohydrate' => 62.00,
                'sodium' => 1580.00,
                'sugar' => 2.70,
                'weight' => 100.00,
            ],
            [
                'id_list_food' => Str::random(10),
                'food_name' => 'Brokoli',
                'food_calories' => 34.00,
                'cholesterol' => 0.00,
                'fat' => 0.37,
                'protein' => 2.82,
                'carbohydrate' => 6.64,
                'sodium' => 33.00,
                'sugar' => 1.70,
                'weight' => 100.00,
            ],
            [
                'id_list_food' => Str::random(10),
                'food_name' => 'Wortel',
                'food_calories' => 41.00,
                'cholesterol' => 0.00,
                'fat' => 0.24,
                'protein' => 0.93,
                'carbohydrate' => 9.58,
                'sodium' => 69.00,
                'sugar' => 4.74,
                'weight' => 100.00,
            ],
            [
                'id_list_food' => Str::random(10),
                'food_name' => 'Jagung Rebus',
                'food_calories' => 96.00,
                'cholesterol' => 0.00,
                'fat' => 1.50,
                'protein' => 3.40,
                'carbohydrate' => 21.00,
                'sodium' => 15.00,
                'sugar' => 4.50,
                'weight' => 100.00,
            ],
            [
                'id_list_food' => Str::random(10),
                'food_name' => 'Semangka',
                'food_calories' => 30.00,
                'cholesterol' => 0.00,
                'fat' => 0.15,
                'protein' => 0.61,
                'carbohydrate' => 7.55,
                'sodium' => 1.00,
                'sugar' => 6.20,
                'weight' => 100.00,
            ],
            [
                'id_list_food' => Str::random(10),
                'food_name' => 'Jeruk',
                'food_calories' => 47.00,
                'cholesterol' => 0.00,
                'fat' => 0.12,
                'protein' => 0.94,
                'carbohydrate' => 11.75,
                'sodium' => 0.00,
                'sugar' => 9.35,
                'weight' => 100.00,
            ],
        ];

        foreach ($foods as $food) {
            DB::table('list_food')->insert([
                'id_list_food' => $food['id_list_food'],
                'food_name' => $food['food_name'],
                'food_calories' => $food['food_calories'],
                'cholesterol' => $food['cholesterol'],
                'fat' => $food['fat'],
                'protein' => $food['protein'],
                'carbohydrate' => $food['carbohydrate'],
                'sodium' => $food['sodium'],
                'sugar' => $food['sugar'],
                'weight' => $food['weight'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
